### ISSUE TITLE
Avoid insecure local registry

### ISSUE THREAD

**Issue by StevenACoffman** [terotuomala/k8s-kustomize-skaffold-k3d-example#9]
Hi! I used your repo as the basis for some work I was doing, and I eventually discovered that you don't actually need to run the insecure local registry. 
If instead, you just don't push for local images, then k3s will just get them from the local docker daemon. This speeds things up quite a bit.

See [local-cluster](https://github.com/GoogleContainerTools/skaffold/blob/master/docs/content/en/docs/environment/local-cluster.md) guide/.

**Comment by terotuomala** [comment]
Thanks for the link, this looks great! I'll update the instructions in near future :)
